console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
final_space = true

[palette]
  blue-bell = '#9aa5ce'
  blue-black = '#565f89'
  celeste-blue = '#b4f9f8'
  light-sky-blue = '#7dcfff'
  main-bg = '#1e1d2c'
  os = '#ACB0BE'
  pastal-grey = '#cfc9c2'
  pistachio-green = '#9ece6a'
  t-background = 'p:main-bg'
  terminal-black = '#454658'
  terminal-blue = '#91b2f4'
  terminal-green = '#b2e1a7'
  terminal-magenta = '#ecc3e4'
  terminal-orange = '#ff991c'
  terminal-red = '#e490a7'
  terminal-white = '#bbc1db'
  terminal-yellow = '#f5e2b4'
  white-blue = '#a5dfd5'

[secondary_prompt]
  template = '➜ '
  foreground = 'p:terminal-blue'
  background = 'transparent'

[transient_prompt]
  template = '➜ '
  foreground = 'p:terminal-blue'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:light-sky-blue'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<b>{{ .Path }}</b> <p:light-sky-blue> </>'
    foreground = 'p:terminal-magenta'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_full'

  [[blocks.segments]]
    template = '({{ .HEAD}})'
    foreground = 'p:pistachio-green'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}', '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}', '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ' '
    foreground = 'p:terminal-red'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:pistachio-green'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:terminal-blue'
    type = 'php'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:terminal-yellow'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:terminal-magenta'
    type = 'julia'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full}}'
    foreground = 'p:terminal-red'
    type = 'ruby'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full}}'
    foreground = 'p:light-sky-blue'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Full }}'
    foreground = 'p:terminal-orange'
    type = 'swift'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' <#fefefe></> {{ .FormattedMs }} '
    foreground = 'p:light-sky-blue'
    type = 'executiontime'
    style = 'agnostic'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      style = 'austin'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '➜'
    foreground = 'p:pistachio-green'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
